OUTPUT_DIR: 'output'
LOG_DIR: 'log'
MODEL: 'AntiFlareNet'
GPUS: '0'
WORKERS: 4
PRINT_FREQ: 100
IMAGE_SIZE: 256

# Data directory setting
DATA_DIR: 'data'
TRAIN_CSV: 'train.csv'
TEST_CSV: 'test.csv'
TRAIN_INPUT_DIR: 'train_input_img'
TRAIN_LABEL_DIR: 'train_label_img'
TEST_INPUT_DIR: 'test_input_img'
TEST_LABEL_DIR: 'test_label_img'
TEST_OUTPUT_DIR: 'sample_submission'

# CUDNN
CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True

# Dataset setting
AUGMENTATION_STRIDE: 128
DATA_CLASS: 'real'
RANDOM_FLIP: True
VALIDATION_RATIO: 0.2

# Training parameter
TRAIN:
  OPTIMIZER: 'adam'
  MOMENTUM: 0.9
  WD: 0.0001
  NESTEROV: False
  GAMMA1: 0.99
  GAMMA2: 0.0
  BATCH_SIZE: 32
  SHUFFLE: True
  BEGIN_EPOCH: 0
  END_EPOCH: 200
  RESUME: True
  LR: 0.001
  LR_STEP: [90, 110]
  LR_FACTOR: 0.1

# Test parameter
TEST:
  BATCH_SIZE: 32
  STATE: 'best'
  FLIP_TEST: False
  POST_PROCESS: False
  MAX_HEIGHT: 3200
  MAX_WIDTH: 4200

# debug
DEBUG:
  DEBUG: True
  SAVE_BATCH_IMAGES: rue