# Key setting
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
MODEL: 'AntiFlareNet'
PATCH_MODEL: 'u-net'
MERGE_MODEL: 'u-net'
GPUS: '0'
WORKERS: 4
PRINT_FREQ: 30

# Data directory setting
DATA_DIR: 'data'
TRAIN_CSV: 'train.csv'
TEST_CSV: 'test.csv'
TRAIN_INPUT_DIR: 'train_input_img'
TRAIN_LABEL_DIR: 'train_label_img'
TEST_INPUT_DIR: 'test_input_img'
TEST_OUTPUT_DIR: 'sample_submission'

# CUDNN
CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True

# Dataset setting
PATCH_SIZE: 256
STRIDE: 128
VALIDATION_RATIO: 0.2

# Data augmentation for Patch Model
AUGMENTATION:
  RANDOM_HORIZONTAL_FLIP: True
  RANDOM_VERTICAL_FLIP: True
  RANDOM_ROTATION: 0.1
  RANDOM_SCALE: 4.0

# Merge model setting
MULTI_SCALE: [1.0, 0.5, 0.25]

# Training parameter
TRAIN:
  OPTIMIZER: 'adam'
  MOMENTUM: 0.9
  WD: 0.0001
  NESTEROV: False
  GAMMA1: 0.99
  GAMMA2: 0.0
  BATCH_SIZE: 128
  SHUFFLE: True
  BEGIN_EPOCH: 0
  END_EPOCH: 10000
  RESUME: True
  LR: 0.001
  LR_STEP: [90, 110]
  LR_FACTOR: 0.1

# Test parameter
TEST:
  BATCH_SIZE: 128
  STATE: 'best'
  FLIP_TEST: False
  POST_PROCESS: False
  MAX_HEIGHT: 3200
  MAX_WIDTH: 4200

# debug
DEBUG:
  DEBUG: True
  SAVE_BATCH_IMAGES: True